Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -78,17 +78,22 @@ jobs:
           echo "Getting artifact ID"
           ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
             "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" \
-            | jq '.artifacts[] | select(.name == "sample-artifact") | .id')
-          echo "ARTIFACT_ID=${ARTIFACT_ID}" >> $GITHUB_ENV
+            | jq -r '.artifacts[] | select(.name == "sample-artifact") | .id')
           echo "Artifact ID: $ARTIFACT_ID"  # Debugging output
+          echo "ARTIFACT_ID=${ARTIFACT_ID}" >> $GITHUB_ENV
 
       - name: Delete artifact
         run: |
           echo "Deleting artifact"
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token ${{ secrets.PAT }}" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}")
-          echo "Response Code: $RESPONSE"  # Debugging output
-          if [ "$RESPONSE" -ne 204 ]; then
-            echo "Failed to delete artifact. HTTP response code: $RESPONSE"
+          if [ -n "${{ env.ARTIFACT_ID }}" ]; then
+            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token ${{ secrets.PAT }}" \
+              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}")
+            echo "Response Code: $RESPONSE"  # Debugging output
+            if [ "$RESPONSE" -ne 204 ]; then
+              echo "Failed to delete artifact. HTTP response code: $RESPONSE"
+              exit 1
+            fi
+          else
+            echo "Artifact ID not found or empty"
             exit 1
           fi
